// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "VBabyKyberHarness__Syms.h"


void VBabyKyberHarness___024root__trace_chg_0_sub_0(VBabyKyberHarness___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void VBabyKyberHarness___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    VBabyKyberHarness___024root__trace_chg_0\n"); );
    // Init
    VBabyKyberHarness___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<VBabyKyberHarness___024root*>(voidSelf);
    VBabyKyberHarness__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    VBabyKyberHarness___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void VBabyKyberHarness___024root__trace_chg_0_sub_0(VBabyKyberHarness___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    VBabyKyberHarness__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VBabyKyberHarness___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[1U])) {
        bufp->chgBit(oldp+0,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber_rst_n));
        bufp->chgIData(oldp+1,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__unnamedblk4__DOT__i),32);
        bufp->chgIData(oldp+2,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__unnamedblk5__DOT__i),32);
        bufp->chgIData(oldp+3,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk4__DOT__i),32);
        bufp->chgIData(oldp+4,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk5__DOT__i),32);
    }
    if (VL_UNLIKELY(((vlSelf->__Vm_traceActivity[1U] 
                      | vlSelf->__Vm_traceActivity[4U]) 
                     | vlSelf->__Vm_traceActivity[6U]))) {
        bufp->chgIData(oldp+5,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__result
                               [0U][0U]),32);
        bufp->chgIData(oldp+6,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__result
                               [0U][1U]),32);
        bufp->chgIData(oldp+7,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__result
                               [0U][2U]),32);
        bufp->chgIData(oldp+8,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__result
                               [0U][3U]),32);
        bufp->chgIData(oldp+9,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__result
                               [1U][0U]),32);
        bufp->chgIData(oldp+10,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__result
                                [1U][1U]),32);
        bufp->chgIData(oldp+11,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__result
                                [1U][2U]),32);
        bufp->chgIData(oldp+12,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__result
                                [1U][3U]),32);
        bufp->chgIData(oldp+13,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [0U][0U][0U]),32);
        bufp->chgIData(oldp+14,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [0U][0U][1U]),32);
        bufp->chgIData(oldp+15,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [0U][0U][2U]),32);
        bufp->chgIData(oldp+16,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [0U][0U][3U]),32);
        bufp->chgIData(oldp+17,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [0U][1U][0U]),32);
        bufp->chgIData(oldp+18,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [0U][1U][1U]),32);
        bufp->chgIData(oldp+19,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [0U][1U][2U]),32);
        bufp->chgIData(oldp+20,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [0U][1U][3U]),32);
        bufp->chgIData(oldp+21,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [1U][0U][0U]),32);
        bufp->chgIData(oldp+22,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [1U][0U][1U]),32);
        bufp->chgIData(oldp+23,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [1U][0U][2U]),32);
        bufp->chgIData(oldp+24,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [1U][0U][3U]),32);
        bufp->chgIData(oldp+25,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [1U][1U][0U]),32);
        bufp->chgIData(oldp+26,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [1U][1U][1U]),32);
        bufp->chgIData(oldp+27,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [1U][1U][2U]),32);
        bufp->chgIData(oldp+28,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext
                                [1U][1U][3U]),32);
    }
    if (VL_UNLIKELY((vlSelf->__Vm_traceActivity[1U] 
                     | vlSelf->__Vm_traceActivity[6U]))) {
        bufp->chgIData(oldp+29,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decimal_value),32);
        bufp->chgCData(oldp+30,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__m_b),4);
        bufp->chgIData(oldp+31,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__temp_m_n[0]),32);
        bufp->chgIData(oldp+32,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__temp_m_n[1]),32);
        bufp->chgIData(oldp+33,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__temp_m_n[2]),32);
        bufp->chgIData(oldp+34,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__temp_m_n[3]),32);
        bufp->chgIData(oldp+35,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult1__polynomial1[0]),32);
        bufp->chgIData(oldp+36,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult1__polynomial1[1]),32);
        bufp->chgIData(oldp+37,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult1__polynomial1[2]),32);
        bufp->chgIData(oldp+38,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult1__polynomial1[3]),32);
        bufp->chgIData(oldp+39,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_mult1__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+40,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_mult1__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+41,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_mult1__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+42,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_mult1__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+43,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult2__polynomial1[0]),32);
        bufp->chgIData(oldp+44,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult2__polynomial1[1]),32);
        bufp->chgIData(oldp+45,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult2__polynomial1[2]),32);
        bufp->chgIData(oldp+46,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult2__polynomial1[3]),32);
        bufp->chgIData(oldp+47,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_mult2__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+48,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_mult2__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+49,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_mult2__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+50,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_mult2__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+51,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added[0]),32);
        bufp->chgIData(oldp+52,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added[1]),32);
        bufp->chgIData(oldp+53,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added[2]),32);
        bufp->chgIData(oldp+54,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added[3]),32);
        bufp->chgIData(oldp+55,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added1[0]),32);
        bufp->chgIData(oldp+56,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added1[1]),32);
        bufp->chgIData(oldp+57,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added1[2]),32);
        bufp->chgIData(oldp+58,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added1[3]),32);
        bufp->chgIData(oldp+59,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__u
                                [0U][0U]),32);
        bufp->chgIData(oldp+60,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__u
                                [0U][1U]),32);
        bufp->chgIData(oldp+61,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__u
                                [0U][2U]),32);
        bufp->chgIData(oldp+62,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__u
                                [0U][3U]),32);
        bufp->chgIData(oldp+63,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__u
                                [1U][0U]),32);
        bufp->chgIData(oldp+64,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__u
                                [1U][1U]),32);
        bufp->chgIData(oldp+65,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__u
                                [1U][2U]),32);
        bufp->chgIData(oldp+66,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__u
                                [1U][3U]),32);
        bufp->chgIData(oldp+67,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__v[0]),32);
        bufp->chgIData(oldp+68,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__v[1]),32);
        bufp->chgIData(oldp+69,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__v[2]),32);
        bufp->chgIData(oldp+70,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__v[3]),32);
        bufp->chgIData(oldp+71,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__added[0]),32);
        bufp->chgIData(oldp+72,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__added[1]),32);
        bufp->chgIData(oldp+73,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__added[2]),32);
        bufp->chgIData(oldp+74,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__added[3]),32);
        bufp->chgIData(oldp+75,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__added1[0]),32);
        bufp->chgIData(oldp+76,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__added1[1]),32);
        bufp->chgIData(oldp+77,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__added1[2]),32);
        bufp->chgIData(oldp+78,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__added1[3]),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[2U])) {
        bufp->chgBit(oldp+79,(vlSelf->BabyKyberHarness__DOT__hostAdapter_io_wbMasterTransmitter_valid));
        bufp->chgBit(oldp+80,(((IData)(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__cycReg) 
                               & (IData)(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__startWBTransaction))));
        bufp->chgBit(oldp+81,(vlSelf->BabyKyberHarness__DOT__hostAdapter_io_wbMasterTransmitter_bits_we));
        bufp->chgCData(oldp+82,(((IData)(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__startWBTransaction)
                                  ? (IData)(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__selReg)
                                  : 0U)),4);
        bufp->chgBit(oldp+83,(vlSelf->BabyKyberHarness__DOT__hostAdapter_io_wbSlaveReceiver_bits_ack));
        bufp->chgBit(oldp+84,(vlSelf->BabyKyberHarness__DOT__deviceAdapter__DOT___T_1));
        bufp->chgBit(oldp+85,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__validReg));
        bufp->chgCData(oldp+86,(((IData)(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__startWBTransaction)
                                  ? (IData)(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__selReg)
                                  : 0U)),8);
        bufp->chgBit(oldp+87,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber_encryption_done));
        bufp->chgCData(oldp+88,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__coefficients),4);
        bufp->chgIData(oldp+89,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__coefficients_scaled[0]),32);
        bufp->chgIData(oldp+90,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__coefficients_scaled[1]),32);
        bufp->chgIData(oldp+91,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__coefficients_scaled[2]),32);
        bufp->chgIData(oldp+92,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__coefficients_scaled[3]),32);
        bufp->chgIData(oldp+93,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__unnamedblk1__DOT__j),32);
        bufp->chgIData(oldp+94,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__unnamedblk2__DOT__i),32);
        bufp->chgIData(oldp+95,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+96,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk1__DOT__unnamedblk2__DOT__j),32);
        bufp->chgBit(oldp+97,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__startWBTransaction));
        bufp->chgIData(oldp+98,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__dataReg),32);
        bufp->chgBit(oldp+99,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__respReg));
        bufp->chgBit(oldp+100,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__stbReg));
        bufp->chgBit(oldp+101,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__cycReg));
        bufp->chgBit(oldp+102,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__weReg));
        bufp->chgIData(oldp+103,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__datReg),32);
        bufp->chgIData(oldp+104,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__adrReg),32);
        bufp->chgCData(oldp+105,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__selReg),4);
        bufp->chgBit(oldp+106,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__stateReg));
        bufp->chgBit(oldp+107,(vlSelf->BabyKyberHarness__DOT__hostAdapter__DOT__readyReg));
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[3U])) {
        bufp->chgBit(oldp+108,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber_key_done));
        bufp->chgBit(oldp+109,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber_decryption_done));
        bufp->chgIData(oldp+110,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_out0[0]),32);
        bufp->chgIData(oldp+111,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_out0[1]),32);
        bufp->chgIData(oldp+112,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_out0[2]),32);
        bufp->chgIData(oldp+113,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_out0[3]),32);
        bufp->chgIData(oldp+114,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_out1[0]),32);
        bufp->chgIData(oldp+115,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_out1[1]),32);
        bufp->chgIData(oldp+116,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_out1[2]),32);
        bufp->chgIData(oldp+117,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__poly_out1[3]),32);
        bufp->chgBit(oldp+118,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT__decryption_done_next));
        bufp->chgIData(oldp+119,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out0[0]),32);
        bufp->chgIData(oldp+120,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out0[1]),32);
        bufp->chgIData(oldp+121,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out0[2]),32);
        bufp->chgIData(oldp+122,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out0[3]),32);
        bufp->chgIData(oldp+123,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out1[0]),32);
        bufp->chgIData(oldp+124,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out1[1]),32);
        bufp->chgIData(oldp+125,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out1[2]),32);
        bufp->chgIData(oldp+126,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out1[3]),32);
        bufp->chgIData(oldp+127,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out2[0]),32);
        bufp->chgIData(oldp+128,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out2[1]),32);
        bufp->chgIData(oldp+129,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out2[2]),32);
        bufp->chgIData(oldp+130,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out2[3]),32);
        bufp->chgIData(oldp+131,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out3[0]),32);
        bufp->chgIData(oldp+132,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out3[1]),32);
        bufp->chgIData(oldp+133,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out3[2]),32);
        bufp->chgIData(oldp+134,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out3[3]),32);
        bufp->chgIData(oldp+135,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out4[0]),32);
        bufp->chgIData(oldp+136,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out4[1]),32);
        bufp->chgIData(oldp+137,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out4[2]),32);
        bufp->chgIData(oldp+138,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out4[3]),32);
        bufp->chgIData(oldp+139,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out5[0]),32);
        bufp->chgIData(oldp+140,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out5[1]),32);
        bufp->chgIData(oldp+141,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out5[2]),32);
        bufp->chgIData(oldp+142,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_out5[3]),32);
        bufp->chgIData(oldp+143,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out0[0]),32);
        bufp->chgIData(oldp+144,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out0[1]),32);
        bufp->chgIData(oldp+145,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out0[2]),32);
        bufp->chgIData(oldp+146,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out0[3]),32);
        bufp->chgIData(oldp+147,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out1[0]),32);
        bufp->chgIData(oldp+148,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out1[1]),32);
        bufp->chgIData(oldp+149,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out1[2]),32);
        bufp->chgIData(oldp+150,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out1[3]),32);
        bufp->chgIData(oldp+151,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out2[0]),32);
        bufp->chgIData(oldp+152,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out2[1]),32);
        bufp->chgIData(oldp+153,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out2[2]),32);
        bufp->chgIData(oldp+154,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out2[3]),32);
        bufp->chgIData(oldp+155,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out3[0]),32);
        bufp->chgIData(oldp+156,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out3[1]),32);
        bufp->chgIData(oldp+157,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out3[2]),32);
        bufp->chgIData(oldp+158,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_out3[3]),32);
        bufp->chgBit(oldp+159,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__key_done_next));
        bufp->chgIData(oldp+160,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk11__DOT__i),32);
        bufp->chgIData(oldp+161,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk11__DOT__unnamedblk12__DOT__j),32);
        bufp->chgIData(oldp+162,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk6__DOT__i),32);
        bufp->chgIData(oldp+163,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk6__DOT__unnamedblk7__DOT__j),32);
        bufp->chgIData(oldp+164,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk6__DOT__unnamedblk7__DOT__unnamedblk8__DOT__k),32);
        bufp->chgIData(oldp+165,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk9__DOT__i),32);
        bufp->chgIData(oldp+166,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__unnamedblk9__DOT__unnamedblk10__DOT__j),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[4U])) {
        bufp->chgIData(oldp+167,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber_addr_Req),32);
        bufp->chgIData(oldp+168,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber_data_Req),32);
        bufp->chgIData(oldp+169,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber_data_Resp),32);
        bufp->chgBit(oldp+170,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber_wen_Req));
        bufp->chgIData(oldp+171,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__secretkey
                                 [0U][0U]),32);
        bufp->chgIData(oldp+172,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__secretkey
                                 [0U][1U]),32);
        bufp->chgIData(oldp+173,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__secretkey
                                 [0U][2U]),32);
        bufp->chgIData(oldp+174,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__secretkey
                                 [0U][3U]),32);
        bufp->chgIData(oldp+175,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__secretkey
                                 [1U][0U]),32);
        bufp->chgIData(oldp+176,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__secretkey
                                 [1U][1U]),32);
        bufp->chgIData(oldp+177,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__secretkey
                                 [1U][2U]),32);
        bufp->chgIData(oldp+178,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__secretkey
                                 [1U][3U]),32);
        bufp->chgIData(oldp+179,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [0U][0U]),32);
        bufp->chgIData(oldp+180,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [0U][1U]),32);
        bufp->chgIData(oldp+181,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [0U][2U]),32);
        bufp->chgIData(oldp+182,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [0U][3U]),32);
        bufp->chgIData(oldp+183,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [1U][0U]),32);
        bufp->chgIData(oldp+184,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [1U][1U]),32);
        bufp->chgIData(oldp+185,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [1U][2U]),32);
        bufp->chgIData(oldp+186,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [1U][3U]),32);
        bufp->chgIData(oldp+187,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [2U][0U]),32);
        bufp->chgIData(oldp+188,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [2U][1U]),32);
        bufp->chgIData(oldp+189,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [2U][2U]),32);
        bufp->chgIData(oldp+190,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [2U][3U]),32);
        bufp->chgIData(oldp+191,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [3U][0U]),32);
        bufp->chgIData(oldp+192,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [3U][1U]),32);
        bufp->chgIData(oldp+193,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [3U][2U]),32);
        bufp->chgIData(oldp+194,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_reg
                                 [3U][3U]),32);
        bufp->chgIData(oldp+195,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_reg
                                 [0U][0U]),32);
        bufp->chgIData(oldp+196,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_reg
                                 [0U][1U]),32);
        bufp->chgIData(oldp+197,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_reg
                                 [0U][2U]),32);
        bufp->chgIData(oldp+198,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_reg
                                 [0U][3U]),32);
        bufp->chgIData(oldp+199,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_reg
                                 [1U][0U]),32);
        bufp->chgIData(oldp+200,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_reg
                                 [1U][1U]),32);
        bufp->chgIData(oldp+201,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_reg
                                 [1U][2U]),32);
        bufp->chgIData(oldp+202,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_reg
                                 [1U][3U]),32);
        bufp->chgIData(oldp+203,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_reg
                                 [0U][0U]),32);
        bufp->chgIData(oldp+204,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_reg
                                 [0U][1U]),32);
        bufp->chgIData(oldp+205,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_reg
                                 [0U][2U]),32);
        bufp->chgIData(oldp+206,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_reg
                                 [0U][3U]),32);
        bufp->chgIData(oldp+207,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_reg
                                 [1U][0U]),32);
        bufp->chgIData(oldp+208,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_reg
                                 [1U][1U]),32);
        bufp->chgIData(oldp+209,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_reg
                                 [1U][2U]),32);
        bufp->chgIData(oldp+210,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_reg
                                 [1U][3U]),32);
        bufp->chgIData(oldp+211,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r
                                 [0U][0U]),32);
        bufp->chgIData(oldp+212,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r
                                 [0U][1U]),32);
        bufp->chgIData(oldp+213,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r
                                 [0U][2U]),32);
        bufp->chgIData(oldp+214,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r
                                 [0U][3U]),32);
        bufp->chgIData(oldp+215,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r
                                 [1U][0U]),32);
        bufp->chgIData(oldp+216,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r
                                 [1U][1U]),32);
        bufp->chgIData(oldp+217,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r
                                 [1U][2U]),32);
        bufp->chgIData(oldp+218,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r
                                 [1U][3U]),32);
        bufp->chgIData(oldp+219,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1
                                 [0U][0U]),32);
        bufp->chgIData(oldp+220,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1
                                 [0U][1U]),32);
        bufp->chgIData(oldp+221,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1
                                 [0U][2U]),32);
        bufp->chgIData(oldp+222,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1
                                 [0U][3U]),32);
        bufp->chgIData(oldp+223,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1
                                 [1U][0U]),32);
        bufp->chgIData(oldp+224,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1
                                 [1U][1U]),32);
        bufp->chgIData(oldp+225,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1
                                 [1U][2U]),32);
        bufp->chgIData(oldp+226,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1
                                 [1U][3U]),32);
        bufp->chgIData(oldp+227,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e2[0]),32);
        bufp->chgIData(oldp+228,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e2[1]),32);
        bufp->chgIData(oldp+229,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e2[2]),32);
        bufp->chgIData(oldp+230,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e2[3]),32);
        bufp->chgIData(oldp+231,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t000),32);
        bufp->chgIData(oldp+232,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t001),32);
        bufp->chgIData(oldp+233,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t002),32);
        bufp->chgIData(oldp+234,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t003),32);
        bufp->chgIData(oldp+235,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t010),32);
        bufp->chgIData(oldp+236,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t011),32);
        bufp->chgIData(oldp+237,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t012),32);
        bufp->chgIData(oldp+238,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t013),32);
        bufp->chgIData(oldp+239,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t020),32);
        bufp->chgIData(oldp+240,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t021),32);
        bufp->chgIData(oldp+241,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t022),32);
        bufp->chgIData(oldp+242,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t023),32);
        bufp->chgIData(oldp+243,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t030),32);
        bufp->chgIData(oldp+244,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t031),32);
        bufp->chgIData(oldp+245,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t032),32);
        bufp->chgIData(oldp+246,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__A_t033),32);
        bufp->chgIData(oldp+247,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_00),32);
        bufp->chgIData(oldp+248,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_01),32);
        bufp->chgIData(oldp+249,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_02),32);
        bufp->chgIData(oldp+250,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_03),32);
        bufp->chgIData(oldp+251,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_10),32);
        bufp->chgIData(oldp+252,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_11),32);
        bufp->chgIData(oldp+253,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_12),32);
        bufp->chgIData(oldp+254,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__s_13),32);
        bufp->chgIData(oldp+255,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_00),32);
        bufp->chgIData(oldp+256,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_01),32);
        bufp->chgIData(oldp+257,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_02),32);
        bufp->chgIData(oldp+258,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_03),32);
        bufp->chgIData(oldp+259,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_10),32);
        bufp->chgIData(oldp+260,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_11),32);
        bufp->chgIData(oldp+261,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_12),32);
        bufp->chgIData(oldp+262,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e_13),32);
        bufp->chgIData(oldp+263,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__message),32);
        bufp->chgIData(oldp+264,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key000),32);
        bufp->chgIData(oldp+265,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key001),32);
        bufp->chgIData(oldp+266,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key002),32);
        bufp->chgIData(oldp+267,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key003),32);
        bufp->chgIData(oldp+268,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key010),32);
        bufp->chgIData(oldp+269,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key011),32);
        bufp->chgIData(oldp+270,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key012),32);
        bufp->chgIData(oldp+271,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key013),32);
        bufp->chgIData(oldp+272,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key020),32);
        bufp->chgIData(oldp+273,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key021),32);
        bufp->chgIData(oldp+274,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key022),32);
        bufp->chgIData(oldp+275,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key023),32);
        bufp->chgIData(oldp+276,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key030),32);
        bufp->chgIData(oldp+277,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key031),32);
        bufp->chgIData(oldp+278,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key032),32);
        bufp->chgIData(oldp+279,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key033),32);
        bufp->chgIData(oldp+280,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key100),32);
        bufp->chgIData(oldp+281,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key101),32);
        bufp->chgIData(oldp+282,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key102),32);
        bufp->chgIData(oldp+283,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key103),32);
        bufp->chgIData(oldp+284,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key110),32);
        bufp->chgIData(oldp+285,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key111),32);
        bufp->chgIData(oldp+286,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key112),32);
        bufp->chgIData(oldp+287,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key113),32);
        bufp->chgIData(oldp+288,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r_00),32);
        bufp->chgIData(oldp+289,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r_01),32);
        bufp->chgIData(oldp+290,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r_02),32);
        bufp->chgIData(oldp+291,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r_03),32);
        bufp->chgIData(oldp+292,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r_10),32);
        bufp->chgIData(oldp+293,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r_11),32);
        bufp->chgIData(oldp+294,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r_12),32);
        bufp->chgIData(oldp+295,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__r_13),32);
        bufp->chgIData(oldp+296,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1_00),32);
        bufp->chgIData(oldp+297,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1_01),32);
        bufp->chgIData(oldp+298,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1_02),32);
        bufp->chgIData(oldp+299,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1_03),32);
        bufp->chgIData(oldp+300,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1_10),32);
        bufp->chgIData(oldp+301,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1_11),32);
        bufp->chgIData(oldp+302,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1_12),32);
        bufp->chgIData(oldp+303,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e1_13),32);
        bufp->chgIData(oldp+304,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e2_0),32);
        bufp->chgIData(oldp+305,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e2_1),32);
        bufp->chgIData(oldp+306,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e2_2),32);
        bufp->chgIData(oldp+307,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__e2_3),32);
        bufp->chgIData(oldp+308,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext000),32);
        bufp->chgIData(oldp+309,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext001),32);
        bufp->chgIData(oldp+310,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext002),32);
        bufp->chgIData(oldp+311,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext003),32);
        bufp->chgIData(oldp+312,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext010),32);
        bufp->chgIData(oldp+313,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext011),32);
        bufp->chgIData(oldp+314,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext012),32);
        bufp->chgIData(oldp+315,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext013),32);
        bufp->chgIData(oldp+316,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext100),32);
        bufp->chgIData(oldp+317,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext101),32);
        bufp->chgIData(oldp+318,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext102),32);
        bufp->chgIData(oldp+319,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__ciphertext103),32);
        bufp->chgIData(oldp+320,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult1__polynomial2[0]),32);
        bufp->chgIData(oldp+321,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult1__polynomial2[1]),32);
        bufp->chgIData(oldp+322,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult1__polynomial2[2]),32);
        bufp->chgIData(oldp+323,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult1__polynomial2[3]),32);
        bufp->chgIData(oldp+324,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult2__polynomial2[0]),32);
        bufp->chgIData(oldp+325,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult2__polynomial2[1]),32);
        bufp->chgIData(oldp+326,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult2__polynomial2[2]),32);
        bufp->chgIData(oldp+327,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__decryption__DOT____Vcellinp__poly_mult2__polynomial2[3]),32);
        bufp->chgIData(oldp+328,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst__polynomial2[0]),32);
        bufp->chgIData(oldp+329,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst__polynomial2[1]),32);
        bufp->chgIData(oldp+330,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst__polynomial2[2]),32);
        bufp->chgIData(oldp+331,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst__polynomial2[3]),32);
        bufp->chgIData(oldp+332,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst1__polynomial2[0]),32);
        bufp->chgIData(oldp+333,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst1__polynomial2[1]),32);
        bufp->chgIData(oldp+334,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst1__polynomial2[2]),32);
        bufp->chgIData(oldp+335,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst1__polynomial2[3]),32);
        bufp->chgIData(oldp+336,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst2__polynomial2[0]),32);
        bufp->chgIData(oldp+337,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst2__polynomial2[1]),32);
        bufp->chgIData(oldp+338,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst2__polynomial2[2]),32);
        bufp->chgIData(oldp+339,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst2__polynomial2[3]),32);
        bufp->chgIData(oldp+340,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst3__polynomial2[0]),32);
        bufp->chgIData(oldp+341,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst3__polynomial2[1]),32);
        bufp->chgIData(oldp+342,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst3__polynomial2[2]),32);
        bufp->chgIData(oldp+343,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst3__polynomial2[3]),32);
        bufp->chgIData(oldp+344,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst4__polynomial2[0]),32);
        bufp->chgIData(oldp+345,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst4__polynomial2[1]),32);
        bufp->chgIData(oldp+346,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst4__polynomial2[2]),32);
        bufp->chgIData(oldp+347,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst4__polynomial2[3]),32);
        bufp->chgIData(oldp+348,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst5__polynomial2[0]),32);
        bufp->chgIData(oldp+349,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst5__polynomial2[1]),32);
        bufp->chgIData(oldp+350,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst5__polynomial2[2]),32);
        bufp->chgIData(oldp+351,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst5__polynomial2[3]),32);
        bufp->chgIData(oldp+352,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult0__polynomial1[0]),32);
        bufp->chgIData(oldp+353,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult0__polynomial1[1]),32);
        bufp->chgIData(oldp+354,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult0__polynomial1[2]),32);
        bufp->chgIData(oldp+355,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult0__polynomial1[3]),32);
        bufp->chgIData(oldp+356,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult0__polynomial2[0]),32);
        bufp->chgIData(oldp+357,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult0__polynomial2[1]),32);
        bufp->chgIData(oldp+358,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult0__polynomial2[2]),32);
        bufp->chgIData(oldp+359,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult0__polynomial2[3]),32);
        bufp->chgIData(oldp+360,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult0__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+361,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult0__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+362,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult0__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+363,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult0__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+364,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult1__polynomial1[0]),32);
        bufp->chgIData(oldp+365,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult1__polynomial1[1]),32);
        bufp->chgIData(oldp+366,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult1__polynomial1[2]),32);
        bufp->chgIData(oldp+367,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult1__polynomial1[3]),32);
        bufp->chgIData(oldp+368,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult1__polynomial2[0]),32);
        bufp->chgIData(oldp+369,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult1__polynomial2[1]),32);
        bufp->chgIData(oldp+370,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult1__polynomial2[2]),32);
        bufp->chgIData(oldp+371,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult1__polynomial2[3]),32);
        bufp->chgIData(oldp+372,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult1__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+373,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult1__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+374,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult1__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+375,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult1__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+376,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult2__polynomial1[0]),32);
        bufp->chgIData(oldp+377,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult2__polynomial1[1]),32);
        bufp->chgIData(oldp+378,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult2__polynomial1[2]),32);
        bufp->chgIData(oldp+379,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult2__polynomial1[3]),32);
        bufp->chgIData(oldp+380,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult2__polynomial2[0]),32);
        bufp->chgIData(oldp+381,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult2__polynomial2[1]),32);
        bufp->chgIData(oldp+382,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult2__polynomial2[2]),32);
        bufp->chgIData(oldp+383,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult2__polynomial2[3]),32);
        bufp->chgIData(oldp+384,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult2__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+385,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult2__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+386,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult2__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+387,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult2__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+388,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult3__polynomial1[0]),32);
        bufp->chgIData(oldp+389,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult3__polynomial1[1]),32);
        bufp->chgIData(oldp+390,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult3__polynomial1[2]),32);
        bufp->chgIData(oldp+391,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult3__polynomial1[3]),32);
        bufp->chgIData(oldp+392,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult3__polynomial2[0]),32);
        bufp->chgIData(oldp+393,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult3__polynomial2[1]),32);
        bufp->chgIData(oldp+394,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult3__polynomial2[2]),32);
        bufp->chgIData(oldp+395,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT____Vcellinp__poly_mult3__polynomial2[3]),32);
        bufp->chgIData(oldp+396,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult3__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+397,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult3__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+398,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult3__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+399,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__keygen__DOT__poly_mult3__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+400,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+401,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__unnamedblk1__DOT__unnamedblk2__DOT__j),32);
        bufp->chgIData(oldp+402,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__unnamedblk3__DOT__i),32);
        bufp->chgIData(oldp+403,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__unnamedblk3__DOT__unnamedblk4__DOT__j),32);
        bufp->chgIData(oldp+404,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__unnamedblk5__DOT__i),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[5U])) {
        bufp->chgIData(oldp+405,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][0U][0U]),32);
        bufp->chgIData(oldp+406,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][0U][1U]),32);
        bufp->chgIData(oldp+407,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][0U][2U]),32);
        bufp->chgIData(oldp+408,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][0U][3U]),32);
        bufp->chgIData(oldp+409,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][1U][0U]),32);
        bufp->chgIData(oldp+410,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][1U][1U]),32);
        bufp->chgIData(oldp+411,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][1U][2U]),32);
        bufp->chgIData(oldp+412,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][1U][3U]),32);
        bufp->chgIData(oldp+413,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][2U][0U]),32);
        bufp->chgIData(oldp+414,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][2U][1U]),32);
        bufp->chgIData(oldp+415,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][2U][2U]),32);
        bufp->chgIData(oldp+416,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][2U][3U]),32);
        bufp->chgIData(oldp+417,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][3U][0U]),32);
        bufp->chgIData(oldp+418,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][3U][1U]),32);
        bufp->chgIData(oldp+419,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][3U][2U]),32);
        bufp->chgIData(oldp+420,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [0U][3U][3U]),32);
        bufp->chgIData(oldp+421,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][0U][0U]),32);
        bufp->chgIData(oldp+422,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][0U][1U]),32);
        bufp->chgIData(oldp+423,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][0U][2U]),32);
        bufp->chgIData(oldp+424,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][0U][3U]),32);
        bufp->chgIData(oldp+425,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][1U][0U]),32);
        bufp->chgIData(oldp+426,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][1U][1U]),32);
        bufp->chgIData(oldp+427,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][1U][2U]),32);
        bufp->chgIData(oldp+428,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][1U][3U]),32);
        bufp->chgIData(oldp+429,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][2U][0U]),32);
        bufp->chgIData(oldp+430,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][2U][1U]),32);
        bufp->chgIData(oldp+431,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][2U][2U]),32);
        bufp->chgIData(oldp+432,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][2U][3U]),32);
        bufp->chgIData(oldp+433,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][3U][0U]),32);
        bufp->chgIData(oldp+434,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][3U][1U]),32);
        bufp->chgIData(oldp+435,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][3U][2U]),32);
        bufp->chgIData(oldp+436,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__public_key
                                 [1U][3U][3U]),32);
        bufp->chgIData(oldp+437,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [0U][0U]),32);
        bufp->chgIData(oldp+438,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [0U][1U]),32);
        bufp->chgIData(oldp+439,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [0U][2U]),32);
        bufp->chgIData(oldp+440,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [0U][3U]),32);
        bufp->chgIData(oldp+441,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [1U][0U]),32);
        bufp->chgIData(oldp+442,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [1U][1U]),32);
        bufp->chgIData(oldp+443,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [1U][2U]),32);
        bufp->chgIData(oldp+444,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [1U][3U]),32);
        bufp->chgIData(oldp+445,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [2U][0U]),32);
        bufp->chgIData(oldp+446,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [2U][1U]),32);
        bufp->chgIData(oldp+447,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [2U][2U]),32);
        bufp->chgIData(oldp+448,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [2U][3U]),32);
        bufp->chgIData(oldp+449,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [3U][0U]),32);
        bufp->chgIData(oldp+450,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [3U][1U]),32);
        bufp->chgIData(oldp+451,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [3U][2U]),32);
        bufp->chgIData(oldp+452,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__transposed_matrix
                                 [3U][3U]),32);
        bufp->chgIData(oldp+453,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst__polynomial1[0]),32);
        bufp->chgIData(oldp+454,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst__polynomial1[1]),32);
        bufp->chgIData(oldp+455,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst__polynomial1[2]),32);
        bufp->chgIData(oldp+456,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst__polynomial1[3]),32);
        bufp->chgIData(oldp+457,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst1__polynomial1[0]),32);
        bufp->chgIData(oldp+458,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst1__polynomial1[1]),32);
        bufp->chgIData(oldp+459,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst1__polynomial1[2]),32);
        bufp->chgIData(oldp+460,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst1__polynomial1[3]),32);
        bufp->chgIData(oldp+461,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst2__polynomial1[0]),32);
        bufp->chgIData(oldp+462,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst2__polynomial1[1]),32);
        bufp->chgIData(oldp+463,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst2__polynomial1[2]),32);
        bufp->chgIData(oldp+464,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst2__polynomial1[3]),32);
        bufp->chgIData(oldp+465,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst3__polynomial1[0]),32);
        bufp->chgIData(oldp+466,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst3__polynomial1[1]),32);
        bufp->chgIData(oldp+467,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst3__polynomial1[2]),32);
        bufp->chgIData(oldp+468,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst3__polynomial1[3]),32);
        bufp->chgIData(oldp+469,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst4__polynomial1[0]),32);
        bufp->chgIData(oldp+470,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst4__polynomial1[1]),32);
        bufp->chgIData(oldp+471,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst4__polynomial1[2]),32);
        bufp->chgIData(oldp+472,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst4__polynomial1[3]),32);
        bufp->chgIData(oldp+473,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst5__polynomial1[0]),32);
        bufp->chgIData(oldp+474,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst5__polynomial1[1]),32);
        bufp->chgIData(oldp+475,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst5__polynomial1[2]),32);
        bufp->chgIData(oldp+476,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__poly_mult_inst5__polynomial1[3]),32);
        bufp->chgIData(oldp+477,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [0U][0U]),32);
        bufp->chgIData(oldp+478,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [0U][1U]),32);
        bufp->chgIData(oldp+479,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [0U][2U]),32);
        bufp->chgIData(oldp+480,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [0U][3U]),32);
        bufp->chgIData(oldp+481,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [1U][0U]),32);
        bufp->chgIData(oldp+482,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [1U][1U]),32);
        bufp->chgIData(oldp+483,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [1U][2U]),32);
        bufp->chgIData(oldp+484,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [1U][3U]),32);
        bufp->chgIData(oldp+485,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [2U][0U]),32);
        bufp->chgIData(oldp+486,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [2U][1U]),32);
        bufp->chgIData(oldp+487,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [2U][2U]),32);
        bufp->chgIData(oldp+488,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [2U][3U]),32);
        bufp->chgIData(oldp+489,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [3U][0U]),32);
        bufp->chgIData(oldp+490,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [3U][1U]),32);
        bufp->chgIData(oldp+491,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [3U][2U]),32);
        bufp->chgIData(oldp+492,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT____Vcellinp__transpose_inst__matrix_in
                                 [3U][3U]),32);
    }
    if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[6U])) {
        bufp->chgIData(oldp+493,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+494,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+495,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+496,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+497,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst1__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+498,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst1__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+499,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst1__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+500,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst1__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+501,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst2__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+502,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst2__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+503,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst2__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+504,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst2__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+505,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst3__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+506,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst3__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+507,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst3__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+508,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst3__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+509,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst4__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+510,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst4__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+511,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst4__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+512,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst4__DOT__temp_result[3]),32);
        bufp->chgIData(oldp+513,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst5__DOT__temp_result[0]),32);
        bufp->chgIData(oldp+514,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst5__DOT__temp_result[1]),32);
        bufp->chgIData(oldp+515,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst5__DOT__temp_result[2]),32);
        bufp->chgIData(oldp+516,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__poly_mult_inst5__DOT__temp_result[3]),32);
    }
    bufp->chgBit(oldp+517,(vlSelf->clock));
    bufp->chgBit(oldp+518,(vlSelf->reset));
    bufp->chgBit(oldp+519,(vlSelf->io_req_ready));
    bufp->chgBit(oldp+520,(vlSelf->io_req_valid));
    bufp->chgIData(oldp+521,(vlSelf->io_req_bits_addrRequest),32);
    bufp->chgIData(oldp+522,(vlSelf->io_req_bits_dataRequest),32);
    bufp->chgCData(oldp+523,(vlSelf->io_req_bits_activeByteLane),4);
    bufp->chgBit(oldp+524,(vlSelf->io_req_bits_isWrite));
    bufp->chgBit(oldp+525,(vlSelf->io_rsp_ready));
    bufp->chgBit(oldp+526,(vlSelf->io_rsp_valid));
    bufp->chgIData(oldp+527,(vlSelf->io_rsp_bits_dataResponse),32);
    bufp->chgBit(oldp+528,(vlSelf->io_rsp_bits_error));
    bufp->chgBit(oldp+529,(vlSelf->io_enable));
    bufp->chgBit(oldp+530,(vlSelf->io_key_enable));
    bufp->chgBit(oldp+531,(vlSelf->io_encryption_enable));
    bufp->chgBit(oldp+532,(vlSelf->io_decryption_enable));
    bufp->chgBit(oldp+533,(vlSelf->io_cio_babykyber_intr_key));
    bufp->chgBit(oldp+534,(vlSelf->io_cio_babykyber_intr_encrypt));
    bufp->chgBit(oldp+535,(vlSelf->io_cio_babykyber_intr_decrypt));
    bufp->chgIData(oldp+536,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added2[0]),32);
    bufp->chgIData(oldp+537,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added2[1]),32);
    bufp->chgIData(oldp+538,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added2[2]),32);
    bufp->chgIData(oldp+539,(vlSelf->BabyKyberHarness__DOT__babykyber__DOT__bkyber__DOT__encryption__DOT__added2[3]),32);
}

void VBabyKyberHarness___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    VBabyKyberHarness___024root__trace_cleanup\n"); );
    // Init
    VBabyKyberHarness___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<VBabyKyberHarness___024root*>(voidSelf);
    VBabyKyberHarness__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[4U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[5U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[6U] = 0U;
}
